### ISSUE TITLE
Re-render for Python 3.7?

### ISSUE THREAD

**Issue by jchodera** [conda-forge/sphinxcontrib-autodoc_doxygen-feedstock#3]
Any chance this can be re-rendered to build Python 3.7 packages?

**Comment by rmcgibbo** [comment]
Is that  something I do manually? I'm not sure how to do it.

**Comment by jchodera** [comment]
I'm not quite sure, but it will likely follow similar lines to this: https://github.com/conda-forge/pybtex-feedstock/issues/2#issuecomment-426272837

**Comment by rmcgibbo** [comment]
@conda-forge-admin please rerender

**Comment by jchodera** [comment]
@rmcgibbo : Seems that hasn't done anything. Any ideas?

**Comment by jchodera** [comment]
We're stuck on just a couple of packages (this one included) to get a Python 3.7 version of OpenMM 7.3 beta built.

**Comment by ocefpaf** [comment]
Done in a few PRs ago.
